package com.pl.erdc2.globalsettings;

import java.util.prefs.PreferenceChangeEvent;
import java.util.prefs.PreferenceChangeListener;
import java.util.prefs.Preferences;
import org.openide.util.NbPreferences;
import org.openide.windows.WindowManager;

final public class ServerInfoPanel extends javax.swing.JPanel {

    private final ServerInfoOptionsPanelController controller;

    ServerInfoPanel(ServerInfoOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        
        Preferences pref = NbPreferences.forModule(ServerInfoPanel.class); 
        String name = pref.get("serverAddressPreference", "");
        
        
        pref.addPreferenceChangeListener(new PreferenceChangeListener() {
            @Override
            public void preferenceChange(PreferenceChangeEvent evt) {
                if (evt.getKey().equals("serverAddressPreference")) {
                    serverAddrField.setText(evt.getNewValue());
                }
            } }); 
        serverAddrField.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverAddrLabel = new javax.swing.JLabel();
        serverAddrField = new javax.swing.JTextField();

        serverAddrLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        org.openide.awt.Mnemonics.setLocalizedText(serverAddrLabel, org.openide.util.NbBundle.getMessage(ServerInfoPanel.class, "ServerInfoPanel.serverAddrLabel.text")); // NOI18N

        serverAddrField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        serverAddrField.setText(org.openide.util.NbBundle.getMessage(ServerInfoPanel.class, "ServerInfoPanel.serverAddrField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(serverAddrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(serverAddrField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverAddrLabel)
                    .addComponent(serverAddrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        serverAddrField.setText(NbPreferences.forModule(ServerInfoPanel.class).get("serverAddressPreference", ""));
    }

    void store() {
        NbPreferences.forModule(ServerInfoPanel.class).put("serverAddressPreference", serverAddrField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField serverAddrField;
    private javax.swing.JLabel serverAddrLabel;
    // End of variables declaration//GEN-END:variables
}
