package com.pl.erdc2.globalsettings;

import java.util.prefs.PreferenceChangeEvent;
import java.util.prefs.PreferenceChangeListener;
import java.util.prefs.Preferences;
import org.openide.util.NbPreferences;
import org.openide.windows.WindowManager;

final public class UserInfoPanel extends javax.swing.JPanel {

    private final UserInfoOptionsPanelController controller;

    UserInfoPanel(UserInfoOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        
        Preferences pref = NbPreferences.forModule(UserInfoPanel.class); 
        String name = pref.get("firstNamePreference", "");
        String lastName = pref.get("lastNamePreference", ""); 
        String indexNo = pref.get("indexNoPreference", ""); 
        String groupID = pref.get("groupIDPreference", "");
        String term = pref.get("termPreference", "");
        //String email = pref.get("emailPreference", "");
        
        
        pref.addPreferenceChangeListener(new PreferenceChangeListener() {
            @Override
            public void preferenceChange(PreferenceChangeEvent evt) {
                if (evt.getKey().equals("firstNamePreference")) {
                    firsNameTextField.setText(evt.getNewValue());
                }
                if (evt.getKey().equals("lastNamePreference")) {
                    lastNameTextField.setText(evt.getNewValue());
                }
                if (evt.getKey().equals("indexNoPreference")) {
                    indexNoTextField.setText(evt.getNewValue());
                }
                if (evt.getKey().equals("groupIDPreference")) {
                    groupIDTextField.setText(evt.getNewValue());
                }
                if (evt.getKey().equals("termPreference")) {
                    termCodeField.setText(evt.getNewValue());
                }
//                if (evt.getKey().equals("emailPreference")) {
//                    emailTextField.setText(evt.getNewValue());
//                }
            } }); 
        firsNameTextField.setText(name); 
        lastNameTextField.setText(lastName); 
        indexNoTextField.setText(indexNo);
        groupIDTextField.setText(groupID);
        termCodeField.setText(term);
        //emailTextField.setText(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        indexNoLabel = new javax.swing.JLabel();
        firsNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        indexNoTextField = new javax.swing.JTextField();
        groupIDLabel = new javax.swing.JLabel();
        groupIDTextField = new javax.swing.JTextField();
        termCodeLabel = new javax.swing.JLabel();
        termCodeField = new javax.swing.JTextField();

        firstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        org.openide.awt.Mnemonics.setLocalizedText(firstNameLabel, org.openide.util.NbBundle.getMessage(UserInfoPanel.class, "UserInfoPanel.firstNameLabel.text")); // NOI18N

        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        org.openide.awt.Mnemonics.setLocalizedText(lastNameLabel, org.openide.util.NbBundle.getMessage(UserInfoPanel.class, "UserInfoPanel.lastNameLabel.text")); // NOI18N

        indexNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        org.openide.awt.Mnemonics.setLocalizedText(indexNoLabel, org.openide.util.NbBundle.getMessage(UserInfoPanel.class, "UserInfoPanel.indexNoLabel.text")); // NOI18N

        firsNameTextField.setEditable(false);
        firsNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        firsNameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firsNameTextField.setText(org.openide.util.NbBundle.getMessage(UserInfoPanel.class, "UserInfoPanel.firsNameTextField.text")); // NOI18N

        lastNameTextField.setEditable(false);
        lastNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        lastNameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastNameTextField.setText(org.openide.util.NbBundle.getMessage(UserInfoPanel.class, "UserInfoPanel.lastNameTextField.text")); // NOI18N

        indexNoTextField.setEditable(false);
        indexNoTextField.setBackground(new java.awt.Color(204, 204, 204));
        indexNoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        indexNoTextField.setText(org.openide.util.NbBundle.getMessage(UserInfoPanel.class, "UserInfoPanel.indexNoTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(groupIDLabel, org.openide.util.NbBundle.getMessage(UserInfoPanel.class, "UserInfoPanel.groupIDLabel.text")); // NOI18N

        groupIDTextField.setEditable(false);
        groupIDTextField.setBackground(new java.awt.Color(204, 204, 204));
        groupIDTextField.setText(org.openide.util.NbBundle.getMessage(UserInfoPanel.class, "UserInfoPanel.groupIDTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(termCodeLabel, org.openide.util.NbBundle.getMessage(UserInfoPanel.class, "UserInfoPanel.termCodeLabel.text")); // NOI18N

        termCodeField.setEditable(false);
        termCodeField.setBackground(new java.awt.Color(204, 204, 204));
        termCodeField.setText(org.openide.util.NbBundle.getMessage(UserInfoPanel.class, "UserInfoPanel.termCodeField.text")); // NOI18N
        termCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termCodeFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameLabel)
                            .addComponent(indexNoLabel)
                            .addComponent(groupIDLabel)
                            .addComponent(termCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupIDTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(indexNoTextField)
                    .addComponent(lastNameTextField)
                    .addComponent(firsNameTextField)
                    .addComponent(termCodeField))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firsNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indexNoLabel)
                    .addComponent(indexNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupIDLabel)
                    .addComponent(groupIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(termCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(termCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void termCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termCodeFieldActionPerformed

    void load() {
        firsNameTextField.setText(NbPreferences.forModule(UserInfoPanel.class).get("firstNamePreference", ""));
        lastNameTextField.setText(NbPreferences.forModule(UserInfoPanel.class).get("lastNamePreference", ""));
        indexNoTextField.setText(NbPreferences.forModule(UserInfoPanel.class).get("indexNoPreference", ""));
        groupIDTextField.setText(NbPreferences.forModule(UserInfoPanel.class).get("groupIDPreference", ""));
        termCodeField.setText(NbPreferences.forModule(UserInfoPanel.class).get("termPreference", ""));
        //emailTextField.setText(NbPreferences.forModule(UserInfoPanel.class).get("emailPreference", ""));
    }

    void store() {
        NbPreferences.forModule(UserInfoPanel.class).put("firstNamePreference", firsNameTextField.getText());
        NbPreferences.forModule(UserInfoPanel.class).put("lastNamePreference", lastNameTextField.getText());
        NbPreferences.forModule(UserInfoPanel.class).put("indexNoPreference", indexNoTextField.getText());
        NbPreferences.forModule(UserInfoPanel.class).put("groupIDPreference", groupIDTextField.getText());
        NbPreferences.forModule(UserInfoPanel.class).put("termPreference", termCodeField.getText());
        //NbPreferences.forModule(UserInfoPanel.class).put("emailPreference", emailTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firsNameTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel groupIDLabel;
    private javax.swing.JTextField groupIDTextField;
    private javax.swing.JLabel indexNoLabel;
    private javax.swing.JTextField indexNoTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField termCodeField;
    private javax.swing.JLabel termCodeLabel;
    // End of variables declaration//GEN-END:variables
}
